package uk.ac.warwick.cs126.util;

import uk.ac.warwick.cs126.interfaces.IKeywordChecker;

public class KeywordChecker implements IKeywordChecker {
    private static final String[] keywords = {
            "abomination",
            "abysmal",
            "acceptable",
            "adequate",
            "alright",
            "amazed",
            "amazing",
            "annoying",
            "appalling",
            "atrocious",
            "average",
            "awful",
            "beautiful",
            "bleurgh",
            "burnt",
            "captivating",
            "cesspool",
            "charming",
            "clueless",
            "cold",
            "corpses",
            "crap",
            "damp",
            "decadent",
            "decent",
            "delectable",
            "delicious",
            "delight",
            "delighted",
            "dire",
            "dirty",
            "disappointing",
            "disastrous",
            "disgrace",
            "disgusting",
            "divine",
            "drained",
            "dreadful",
            "dry",
            "dump",
            "electric",
            "enchanting",
            "enjoyable",
            "excellence",
            "excellent",
            "exquisite",
            "extravagant",
            "fascinating",
            "filthy",
            "flavourful",
            "frozen",
            "gem",
            "good",
            "great",
            "grim",
            "gross",
            "happy",
            "heart",
            "hopeless",
            "horrible",
            "icky",
            "inadequate",
            "incredible",
            "inedible",
            "interesting",
            "lost",
            "lovely",
            "luscious",
            "lush",
            "mediocre",
            "mouth-watering",
            "mundane",
            "musty",
            "nasty",
            "odious",
            "ok",
            "okay",
            "overhyped",
            "overpriced",
            "overrated",
            "paradise",
            "passable",
            "perfect",
            "pleasant",
            "positive",
            "rancid",
            "repulsive",
            "revolting",
            "roughly",
            "rubbish",
            "rude",
            "satisfactory",
            "savoury",
            "shambles",
            "slow",
            "slum",
            "so-so",
            "sublime",
            "succulent",
            "sucked",
            "sumptuous",
            "terrible",
            "tired",
            "trash",
            "traumatizing",
            "unappetizing",
            "under-seasoned",
            "undercooked",
            "unpleasant",
            "unprofessional",
            "unsatisfying",
            "welcoming",
            "wonderful",
            "worst",
            "yuck",
            "yummy"
    };

    public KeywordChecker() {
        // Initialise things here
    }

    public boolean isAKeyword(String word) {
        // TODO
        return false;
    }
}